# Generated by Django 2.0.5 on 2018-06-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membergroupform',
            name='membergroup_member_ids',
        ),
    ]
