# Generated by Django 2.0.6 on 2018-06-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_remove_membergroupform_membergroup_member_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberGroupForm',
        ),
    ]
