INSERT INTO ranking_account (account_type, account_email, account_salt, account_password, account_status, account_linked_id) VALUES ('admin', 'test@sailing_dinosaurs.com', 'sljdbkvkakfsbdhvk', 'a25c78192f2a235a801b5cbbb4f4a40719c7644424b97b06808a39a0', 'active',  -1);
INSERT INTO ranking_eventtype (event_type_name) VALUES ('fleet');
INSERT INTO ranking_eventtype (event_type_name) VALUES ('group');
INSERT INTO ranking_season (season_name) VALUES ('Fall 2017');
INSERT INTO ranking_season (season_name) VALUES ('Winter 2017');
INSERT INTO ranking_season (season_name) VALUES ('Spring 2018');
INSERT INTO ranking_season (season_name) VALUES ('Summer 2018');
INSERT INTO ranking_season (season_name) VALUES ('Fall 2018');
INSERT INTO ranking_region (region_name) VALUES ('British Columbia');
INSERT INTO ranking_region (region_name) VALUES ('Alberta');
INSERT INTO ranking_region (region_name) VALUES ('Manitoba');
INSERT INTO ranking_region (region_name) VALUES ('Saskathewan');
INSERT INTO ranking_region (region_name) VALUES ('Other East Territories');
INSERT INTO ranking_region (region_name) VALUES ('Ontario');
INSERT INTO ranking_region (region_name) VALUES ('Quebec');
INSERT INTO ranking_region (region_name) VALUES ('Maritime Provinces');
INSERT INTO ranking_scoremapping (score_name, score_value) VALUES ('OCF', -10);
INSERT INTO ranking_scoremapping (score_name, score_value) VALUES ('DNF', -10);
INSERT INTO ranking_scoremapping (score_name, score_value) VALUES ('DNS', -10);