from .AccountAPI import AccountAPI
from .EventActivityAPI import EventActivityAPI
from .ConfigAPI import ConfigAPI
from .EventAPI import EventAPI
from .EventTagAPI import EventTagAPI
from .EventTeamAPI import EventTeamAPI
from .EventTypeAPI import EventTypeAPI
from .LogAPI import LogAPI
from .MemberAPI import MemberAPI
from .MemberGroupAPI import MemberGroupAPI
from .NewsBumpAPI import NewsBumpAPI
from .NewsCommentAPI import NewsCommentAPI
from .NewsPostAPI import NewsPostAPI
from .RegionAPI import RegionAPI
from .SchoolAPI import SchoolAPI
from .ScoreMappingAPI import ScoreMappingAPI
from .SeasonAPI import SeasonAPI
from .SummaryAPI import SummaryAPI
from .TeamAPI import TeamAPI
