from .RegattasPageAPI import RegattasPageAPI
from .ScoringPageAPI import ScoringPageAPI
from .RotationPageAPI import RotationPageAPI
from .LeaguePageAPI import LeaguePageAPI
from .SchoolsPageAPI import SchoolsPageAPI
from .SchoolDetailsPageAPI import SchoolDetailsPageAPI
from .SeasonPageAPI import SeasonPageAPI
from .NewsPageAPI import NewsPageAPI
from .SpecificNewsPageAPI import SpecificNewsPageAPI
