# Generated by Django 2.0.5 on 2018-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGroupForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membergroup_member_ids', models.CharField(max_length=200)),
            ],
        ),
    ]
