# Generated by Django 2.2.1 on 2019-05-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicsa_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='score_override_value',
            field=models.IntegerField(default=0),
        ),
    ]
