# Generated by Django 2.2.3 on 2019-07-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicsa_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_override_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_league_score',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_override_league_score',
            field=models.FloatField(default=-1),
        ),
    ]
