# Generated by Django 2.2.3 on 2019-07-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicsa_ranking', '0002_auto_20190527_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_override_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_league_score',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_override_league_score',
            field=models.FloatField(default=-1),
        ),
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_team_name', models.CharField(default='School Team Name', max_length=200)),
                ('member_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cicsa_ranking.MemberGroup')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cicsa_ranking.School')),
            ],
        ),
    ]
