# Generated by Django 2.2.1 on 2019-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicsa_ranking', '0002_auto_20190527_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_season_score',
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_event_override_league_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.IntegerField(default=0),
        ),
    ]
