# Generated by Django 2.2.3 on 2019-07-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicsa_ranking', '0003_auto_20190716_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteam',
            name='member_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_teams', to='cicsa_ranking.MemberGroup'),
        ),
        migrations.AlterField(
            model_name='schoolteam',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_teams', to='cicsa_ranking.School'),
        ),
    ]
