# Generated by Django 2.0.5 on 2018-06-02 03:55

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('account_email', models.EmailField(max_length=254)),
                ('account_salt', models.CharField(max_length=200)),
                ('account_password', models.CharField(max_length=200)),
                ('account_status', models.CharField(max_length=50)),
                ('account_linked_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=1500)),
                ('event_status', models.CharField(max_length=50)),
                ('event_type', models.IntegerField()),
                ('event_host', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=50)),
                ('event_region', models.IntegerField()),
                ('event_boat_number', models.IntegerField()),
                ('event_rotation_detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('event_start_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 2, 3, 55, 52, 596147, tzinfo=utc))),
                ('event_end_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 2, 3, 55, 52, 596194, tzinfo=utc))),
                ('event_teams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('event_tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('event_summary', models.CharField(max_length=50)),
                ('event_create_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 2, 3, 55, 52, 596327, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_activity_event_parent', models.IntegerField()),
                ('event_activity_event_tag', models.CharField(max_length=100)),
                ('event_activity_name', models.CharField(max_length=100)),
                ('event_activity_order', models.IntegerField()),
                ('event_activity_result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('event_activity_type', models.CharField(max_length=200)),
                ('event_activity_note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_creator', models.IntegerField()),
                ('log_content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('log_type', models.CharField(max_length=50)),
                ('log_create_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 2, 3, 55, 52, 609144, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('member_school', models.IntegerField()),
                ('member_email', models.EmailField(max_length=254)),
                ('member_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membergroup_member_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_region', models.IntegerField()),
                ('school_status', models.CharField(max_length=50)),
                ('school_season_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_event_parent', models.IntegerField()),
                ('summary_result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('summary_score', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_school', models.IntegerField()),
                ('team_status', models.CharField(max_length=50)),
            ],
        ),
    ]
