# Generated by Django 2.0.5 on 2018-06-11 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20180611_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membergroup',
            old_name='membergroup_member_ids',
            new_name='member_group_member_ids',
        ),
        migrations.RenameField(
            model_name='membergroup',
            old_name='membergroup_name',
            new_name='member_group_name',
        ),
        migrations.RenameField(
            model_name='membergroup',
            old_name='membergroup_school',
            new_name='member_group_school',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 11, 21, 0, 14, 574688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 11, 21, 0, 14, 574529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 11, 21, 0, 14, 574477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 11, 21, 0, 14, 589835, tzinfo=utc)),
        ),
    ]
