# Generated by Django 2.0.5 on 2018-06-12 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20180611_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_tag_name', models.CharField(max_length=200)),
                ('event_tag_parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_team_id', models.IntegerField()),
                ('event_team_member_group_id', models.IntegerField()),
                ('event_team_tag_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_tag',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_teams',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='summary_result',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='summary_score',
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_event_override_ranking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_event_ranking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_event_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_event_tag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_event_team',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 4, 27, 27, 661197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 4, 27, 27, 661148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 4, 27, 27, 661100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_summary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 4, 27, 27, 679019, tzinfo=utc)),
        ),
    ]
