# Generated by Django 2.0.5 on 2018-06-12 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_auto_20180612_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtag',
            old_name='event_tag_parent',
            new_name='event_tag_event_id',
        ),
        migrations.AddField(
            model_name='eventteam',
            name='event_team_event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 6, 9, 32, 709240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 6, 9, 32, 709188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 6, 9, 32, 709135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 6, 9, 32, 725201, tzinfo=utc)),
        ),
    ]
