# Generated by Django 2.0.6 on 2018-06-21 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_auto_20180621_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_summary',
        ),
        migrations.RemoveField(
            model_name='eventteam',
            name='event_team_event_id',
        ),
        migrations.RemoveField(
            model_name='eventteam',
            name='event_team_tag_id',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='summary_event_tag',
        ),
        migrations.AddField(
            model_name='eventteam',
            name='event_team_event_activity_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 21, 14, 33, 33, 497807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventteam',
            name='event_team_member_group_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 21, 14, 33, 33, 513296, tzinfo=utc)),
        ),
    ]
