# Generated by Django 2.0.6 on 2018-06-25 00:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_auto_20180621_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 25, 0, 45, 34, 59173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 25, 0, 45, 34, 72727, tzinfo=utc)),
        ),
    ]
