# Generated by Django 2.0.6 on 2018-06-25 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_auto_20180625_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 25, 5, 7, 10, 11241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 25, 5, 7, 10, 24548, tzinfo=utc)),
        ),
    ]
