# Generated by Django 2.0.5 on 2018-07-14 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0012_auto_20180625_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_default_team_name',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 14, 3, 42, 5, 608233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventactivity',
            name='event_activity_event_tag',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventactivity',
            name='event_activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 14, 3, 42, 5, 641030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_override_ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_event_team',
            field=models.IntegerField(default=0),
        ),
    ]
