# Generated by Django 2.0.5 on 2018-07-14 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0013_auto_20180714_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='summary_event_team',
            new_name='summary_event_school',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 14, 4, 50, 19, 873749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 14, 4, 50, 19, 894838, tzinfo=utc)),
        ),
    ]
