from api.client_api.page_api.NewsPageAPI import NewsPageAPI
from api.client_api.page_api.SpecificNewsPageAPI import SpecificNewsPageAPI
from api.client_api.process_api.SpecificNewsProcessAPI import SpecificNewsProcessAPI